// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Profile: typeof import('./src/components/Profile/Profile.vue')['default']
    Shadow: typeof import('./src/components/Shadow/Shadow.vue')['default']
  }
}

export { }
